name: Build Kivy App

on:
  push:
    branches:
      - main  # Change to your default branch
  pull_request:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use a compatible Python version

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip

      - name: Build the App
        run: |
          cd path/to/your/app  # Change this to your app directory
          buildozer android debug  # You can change this to `release` if needed

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: myapp-apk
          path: ${{ steps.buildozer.outputs.filename }}  # Change this to match your APK output location
